# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hikari.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1080, 960)
        MainWindow.setStyleSheet("#MainWindow {background-image: url('Cssbackgrounds/bgcolor.jpg'); background-repeat: repeat-x; background-position: bottom;} QLineEdit {border-radius: 10px; border: 1px solid green; font-size: 24px; padding-left: 10px;} QLabel {font-family: 'Arial'; font-size: 24px;} #ImageHolder {margin-left: 100px; margin-top: 20px;}")
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icons\Hikarimanlogo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.listView = QtGui.QListView(self.centralwidget)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.listView.setStyleSheet("#listView { background-image: url('Cssbackgrounds/Greeny.png'); background-repeat: no-repeat; background-position: right bottom; background-color: White; border:1px solid green; font-size: 24px;}")
        self.listView.setWindowTitle('Database Browser')
        self.listView.clicked.connect(self.GetData)
        self.horizontalLayout.addWidget(self.listView)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.TitleLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName(_fromUtf8("TitleLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.TitleLabel)
        self.TitleLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.TitleLineEdit.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TitleLineEdit.setFont(font)
        self.TitleLineEdit.setFrame(False)
        self.TitleLineEdit.setObjectName(_fromUtf8("TitleLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.TitleLineEdit)
        self.TypeLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.TypeLabel.setFont(font)
        self.TypeLabel.setObjectName(_fromUtf8("TypeLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.TypeLabel)
        self.TypeLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.TypeLineEdit.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TypeLineEdit.setFont(font)
        self.TypeLineEdit.setFrame(False)
        self.TypeLineEdit.setObjectName(_fromUtf8("TypeLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.TypeLineEdit)
        self.AuthorStudioLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.AuthorStudioLabel.setFont(font)
        self.AuthorStudioLabel.setObjectName(_fromUtf8("AuthorStudioLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.AuthorStudioLabel)
        self.AuthorStudioLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.AuthorStudioLineEdit.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AuthorStudioLineEdit.setFont(font)
        self.AuthorStudioLineEdit.setInputMask(_fromUtf8(""))
        self.AuthorStudioLineEdit.setFrame(False)
        self.AuthorStudioLineEdit.setObjectName(_fromUtf8("AuthorStudioLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.AuthorStudioLineEdit)
        self.GenreLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.GenreLabel.setFont(font)
        self.GenreLabel.setObjectName(_fromUtf8("GenreLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.GenreLabel)
        self.GenreLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.GenreLineEdit.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GenreLineEdit.setFont(font)
        self.GenreLineEdit.setFrame(False)
        self.GenreLineEdit.setObjectName(_fromUtf8("GenreLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.GenreLineEdit)
        self.volumesLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.volumesLabel.setFont(font)
        self.volumesLabel.setObjectName(_fromUtf8("volumesLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.volumesLabel)
        self.VolumesLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.VolumesLineEdit.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.VolumesLineEdit.setFont(font)
        self.VolumesLineEdit.setFrame(False)
        self.VolumesLineEdit.setObjectName(_fromUtf8("VolumesLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.VolumesLineEdit)
        self.chaptersLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chaptersLabel.setFont(font)
        self.chaptersLabel.setObjectName(_fromUtf8("chaptersLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.chaptersLabel)
        self.ChaptersLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.ChaptersLineEdit.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ChaptersLineEdit.setFont(font)
        self.ChaptersLineEdit.setFrame(False)
        self.ChaptersLineEdit.setObjectName(_fromUtf8("ChaptersLineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.ChaptersLineEdit)
        self.statusLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.statusLabel)
        self.StatusLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.StatusLineEdit.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StatusLineEdit.setFont(font)
        self.StatusLineEdit.setFrame(False)
        self.StatusLineEdit.setObjectName(_fromUtf8("StatusLineEdit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.StatusLineEdit)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.EditButton = QtGui.QPushButton(self.centralwidget)
        self.EditButton.setObjectName(_fromUtf8("EditButton"))
        self.EditButton.clicked.connect(self.Editbutton)
        self.horizontalLayout_2.addWidget(self.EditButton)
        self.DeleteButton = QtGui.QPushButton(self.centralwidget)
        self.DeleteButton.setObjectName(_fromUtf8("DeleteButton"))
        self.DeleteButton.clicked.connect(self.Deletebutton)
        self.horizontalLayout_2.addWidget(self.DeleteButton)
        self.formLayout.setLayout(9, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 2000, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        
        self.ImageHolder = QtGui.QLabel()
        self.ImageHolder.setObjectName("ImageHolder")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole,self.ImageHolder)
        self.formLayout.setItem(8, QtGui.QFormLayout.FieldRole, spacerItem)
        self.horizontalLayout.addLayout(self.formLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        
        
        ##MENUBAR
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1034, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_Item = QtGui.QAction(MainWindow)
        self.actionAdd_Item.setWhatsThis(_fromUtf8(""))
        self.actionAdd_Item.setShortcut(_fromUtf8(""))
        self.actionAdd_Item.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionAdd_Item.setObjectName(_fromUtf8("actionAdd_Item"))
        self.actionAdd_Item.triggered.connect(self.AddItem)
        self.actionExit_Application = QtGui.QAction(MainWindow)
        self.actionExit_Application.setShortcut(_fromUtf8(""))
        self.actionExit_Application.setObjectName(_fromUtf8("actionExit_Application"))
        self.actionExit_Application.triggered.connect(self.ExitApp)
        self.actionView_Group = QtGui.QActionGroup(self.menuView)
        self.SelectAll = "Show All"
        self.selectAnime = "Anime"
        self.selectManga = "Manga"
        self.selectlightwebnovel = "Light\Web Novel"
        self.actionSelectAll = QtGui.QAction(self.SelectAll, self.menuView, checkable=True)
        self.actionSelectAll.setChecked(True)
        self.actionSelectAnime = QtGui.QAction(self.selectAnime, self.menuView, checkable=True)
        self.actionSelectManga = QtGui.QAction(self.selectManga, self.menuView, checkable=True)
        self.actionSelectLightWebNovel = QtGui.QAction(self.selectlightwebnovel, self.menuView, checkable=True)
        self.menuView.addAction(self.actionSelectAll)
        self.menuView.addAction(self.actionSelectAnime)
        self.menuView.addAction(self.actionSelectManga)
        self.menuView.addAction(self.actionSelectLightWebNovel)
        self.actionView_Group.addAction(self.actionSelectAll)
        self.actionView_Group.addAction(self.actionSelectAnime)
        self.actionView_Group.addAction(self.actionSelectManga)
        self.actionView_Group.addAction(self.actionSelectLightWebNovel)
        self.actionView_Group.setExclusive(True)
        self.actionView_Group.triggered.connect(self.FilteredListResult)
        

        
        self.menu_File.addAction(self.actionAdd_Item)
        self.menu_File.addAction(self.actionExit_Application)
        

        
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Hikari", None))
        self.TitleLabel.setText(_translate("MainWindow", "Title", None))
        self.TypeLabel.setText(_translate("MainWindow", "Type", None))
        self.AuthorStudioLabel.setText(_translate("MainWindow", "Author/Studio", None))
        self.GenreLabel.setText(_translate("MainWindow", "Genre", None))
        self.volumesLabel.setText(_translate("MainWindow", "Volumes", None))
        self.chaptersLabel.setText(_translate("MainWindow", "Chapters", None))
        self.statusLabel.setText(_translate("MainWindow", "Status", None))
        self.EditButton.setText(_translate("MainWindow", "Edit", None))
        self.DeleteButton.setText(_translate("MainWindow", "Delete", None))
        self.menu_File.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.actionAdd_Item.setText(_translate("MainWindow", "Add Item", None))
        self.actionAdd_Item.setStatusTip(_translate("MainWindow", "Add an Item to the Database", None))
        self.actionExit_Application.setText(_translate("MainWindow", "Exit Application", None))
        self.actionExit_Application.setStatusTip(_translate("MainWindow", "Close Applicatiom", None))
        
        self.actionSelectAll.setText(_translate("MainWindow", "Show All", None))
        self.actionSelectAll.setStatusTip(_translate("MainWindow", "Filter All", None))        
        self.actionSelectAnime.setText(_translate("MainWindow", "Show Anime", None))
        self.actionSelectAnime.setStatusTip(_translate("MainWindow", "Filter Anine", None))
        self.actionSelectManga.setText(_translate("MainWindow", "Show Manga", None))
        self.actionSelectManga.setStatusTip(_translate("MainWindow", "Filter Manga", None))
        self.actionSelectLightWebNovel.setText("Show Light Novel")
        self.actionSelectLightWebNovel.setStatusTip(_translate("MainWindow", "Filter Light and Web Novel", None))
        

        
        
##Set Taskbar Icon for Windows
import ctypes
myappid = 'Cardoza.Project.Hikari.version-1.1'
ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)        

